name: Merge and save AppMap archives from a matrix job
description: |
  Merge AppMap archives from a matrix job. This action should be run in a subsequent build job,
  after the `archive` action has been run for each matrix job. The archives are merged into a single archive, and
  then saved as an artifact. The `merge` action can be followed with the `getappmap/analyze-action`, if 
  a pull request is being analyzed.
inputs:
  directory:
    description: Command working directory.
  archive-count:
    description: |
      Number of archive files to merge. This value should be the same as the number of matrix jobs.
    required: true
  revision:
    description: |
      Revision (commit SHA) to name the AppMap archive with. The default is the GITHUB_SHA.
      Under normal circumstances, the default value is correct and this input does not need to be specified.
  github-token:
    description: |
      The GitHub token to use with the GitHub API to pull AppMap archives from build artifacts.
      Most commonly, you'll use `secrets.GITHUB_TOKEN`, which is automatically provided by GitHub.
    default: ${{ github.token }}
  verbose:
    description: Enable verbose logging.
runs:
  using: 'node16'
  main: '../dist/merge/index.js'
