name: Build and save an AppMap archive
branding:
  icon: archive
  color: purple
description: |
  Build an AppMap archive from a test run, to facilitate AppMap Analysis.
inputs:
  directory:
    description: Command working directory.
  archive-id:
    description: |
      0-based numerical id of a matrix job. This id is used to store the AppMap archive in the action cache.
      Once the matrix jobs complete, the `merge` action can be used to merge the archives into a single archive,
      and then save it as an artifact. If `archive-id` is set, the archive is saved to the cache. Otherwise,
      it's uploaded to the artifact store. For a non-matrix job, `archive-id` should not be used.
  revision:
    description: |
      Revision (commit SHA) to name the AppMap archive with. The default is the GITHUB_SHA.
      Under normal circumstances, the default value is correct and this input does not need to be specified.
  thread-count:
    description:
      Number of worker threads to use for processing the archive. Defaults to the number of CPUs /
      cores, as reported by Node.js. If the worker machine has a high number of CPUs/cores, the
      archive action may become I/O-bound rather than CPU-bound, and better performance might be
      obtained by setting this value to a lower number.
  verbose:
    description: Enable verbose logging.
runs:
  using: 'node16'
  main: 'dist/archive/index.js'
