#!/usr/bin/env bash

cd tmp/appmap
tar czf appmaps.tar.gz **/*.appmap.json
echo {\"name\": \"Dummy / sample archive created on $(date)\"} > appmap_archive.json
tar cf 402dec8.tar appmaps.tar.gz appmap_archive.json
cd -

mkdir -p .appmap/archive/full
mv tmp/appmap/402dec8.tar .appmap/archive/full/
