#!/usr/bin/env bash

set -ex

# If argument 1 is not 'archive', raise an error
if [ "$1" != "archive" ]; then
  echo "Error: first argument must be 'archive'"
  exit 1
fi

# If there is an argument after --revision, name the archive after it.
# Otherwise, name it '402dec8'.\
flag=$2
if [ "$flag" = "--revision" ]; then
  shift
  revision=$2
  shift
else
  revision=402dec8
fi

cd tmp/appmap
tar czf appmaps.tar.gz **/*.appmap.json
echo {\"name\": \"Dummy / sample archive created on $(date)\"} > appmap_archive.json
tar cf $revision.tar appmaps.tar.gz appmap_archive.json
cd -

mkdir -p .appmap/archive/full
mv tmp/appmap/$revision.tar .appmap/archive/full/
