name: CI

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'

env:
  APPMAP_TELEMETRY_DISABLED: 'true'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # This is needed to see the version history, because
          # checkout action doesn't fetch the base or head branches
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Install dependency libraries
        run: yarn install

      - name: Install AppMap tools
        uses: getappmap/install-action@main
        with:
          tools-url: https://github.com/getappmap/appmap-js/releases/download/%40appland%2Fappmap-faster-v1.0-pre.8/appmap-linux-x64
          github-token: ${{ secrets.GITHUB_TOKEN }}
          project-type: yarn

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

      - name: Archive AppMaps
        if: github.event_name != 'pull_request'
        uses: ./

      - name: Analyze AppMaps
        uses: getappmap/analyze-action@main
        if: (success() || failure()) && github.event_name == 'pull_request'
        with:
          base-revision: ${{ github.event.pull_request.base.sha }}
          head-revision: ${{ github.event.pull_request.head.sha }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build GitHub action
        run: yarn package

      - name: Commit changes
        # If you forgot to package the distribution, you'll see a commit added to your PR
        uses: EndBug/add-and-commit@v7
        with:
          add: dist
          message: 'chore: Packaged distribution of the GitHub action'

      - uses: rickstaa/action-create-tag@v1
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          tag: v1
          tag_exists_error: false
