name: CI

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'

env:
  APPMAP_TELEMETRY_DISABLED: 'true'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # This is needed to see the version history, because
          # checkout action doesn't fetch the base or head branches
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Install dependency libraries
        run: yarn install

      - name: Install AppMap tools
        uses: getappmap/install-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          project-type: yarn

      - name: Build
        run: yarn package

      - name: Test
        run: yarn appmap

      - name: Archive AppMaps
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
